//Get clients
db.clients.find()


//Get by estbMnemonic MF
db.clients.find({
    "estbMnemonic": "MF"
})


//Count campaning
db.clients.aggregate([
    { 
        $match: { "estbMnemonic": "MF" } // Filtra el documento por "estbMnemonic"
    },
    { 
        $project: { 
            campaignsCount: { $size: "$channels.email.campaigns" } // Cuenta los elementos dentro de "campaigns"
        }
    }
]);



//update por nemonic 001-SOLICITUD-FIRMA-USER
db.clients.updateOne(
    { 
        "estbMnemonic": "MF",
        "channels.email.campaigns.nemonic": "001-SOLICITUD-FIRMA-USER"
    },
    { 
        $set: { 
            "channels.email.campaigns.$.message": "subject¦MercadoFin: [Solicitud #_idSolicitud] ¡Tu solicitud de firma electrónica está en proceso!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<body style='font-family: Arial, sans-serif; margin: 0; padding: 0; color: #333333;'><div style='width: 100%; padding: 20px;'> <div><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; margin-top: 20px; font-weight: 600; '>¡Tu solicitud para _transaction ha sido enviada!</div> <div style='margin-top: 20px;'> <p>La solicitud para la generación de tu firma <b>electrónica P12</b> ha sido enviada y está en proceso. Para completar este trámite, en breve recibirás un <b>mensaje con el link de pago para tarjeta de crédito o débito.</b></p> <p>📌 <b>Detalles de la solicitud:</b> <br> <ul><li><b>Número de solicitud:</b> #_idSolicitud</li> <li><b>Estado actual:</b> Pendiente de pago</li> <li><b>Tipo de firma:</b> Digital P12</li></ul></p> <p> 📌 <b>Próximos pasos:</b> <br> <ul><li>⿡ Revisa tu bandeja de entrada en las próximas horas para recibir el mensaje con el link de pago.</li> <li>⿢ Accede al enlace y completa el pago con tarjeta de crédito o débito.</li> <li>⿣ Una vez confirmado el pago, recibirás una notificación cuando tu firma electrónica esté lista para su uso.</li></ul></p>  <p>📩 <b>¿Necesitas ayuda?</b> <br><br> Si tienes dudas o necesitas asistencia, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p></div> <div style='margin-top: 20px; font-size: 14px;'>Saludos, <br><br> El equipo de <b>MercadoFin</b></div> </div></body>"
        }
    }
)



//Fitro por nemonic 001-SOLICITUD-FIRMA-USER
db.clients.findOne(
    { 
        "estbMnemonic": "MF",
        "channels.email.campaigns.nemonic": "001-SOLICITUD-FIRMA-USER"
    },
    { 
        "channels.email.campaigns.$": 1, 
        "_id": 0 
    }
)



//Insert client 
db.clients.insertOne({
	"estbMnemonic" : "MF",
	"channels" : {
		"email" : {
			"providers" : {
				
			},
			"campaigns" : [
				{
					"nemonic" : "001-INIT",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: [Solicitud #_idTransaction] Inicia la firma de tu Seguro Vehicular|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='width: 100%;font-family: Arial, sans-serif; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%; height: auto;'></div><div style='font-weight: 600;font-size: 20px; margin-top: 20px;'>¡Estás a un paso de obtener tu seguro!</div> <div style='font-family:sans-serif;width:500px; padding:10px'> <p style='text-align:justify;font-weight:lighter'>Estimado(a) _name, <br><br>Tu formulario de vinculación y documentos asociados a la Solicitud #_idTransaction, han sido generados y están listos para ser firmados. Para completar el proceso y formalizar tu Seguro Vehicular, sigue estos pasos: <br> <p><b>🔗 Accede al portal de:</b> <a href=\"_contractURL\">Firma Segura</a></p> <p><b>📌 ¿Cómo completar la firma?</b></p> <ul> <li>1️⃣ Haz clic en el enlace para acceder a la plataforma de FirmaSegura.</li> <li>2️⃣ Inicia sesión con tu correo registrado en MercadoFin.</li> <li>3️⃣ Revisa los documentos generados, incluyendo el formulario de vinculación.</li> <li>4️⃣ Firma electrónicamente siguiendo las instrucciones en pantalla.</li> <li>5️⃣ Confirma la finalización del proceso y aguarda la notificación de aprobación de la póliza.</li> </ul> <b>✅ Importante:</b> <ul> <li>Asegúrate de completar la firma dentro del tiempo estipulado para evitar retrasos en la emisión de tu póliza.</li> <li>Recibirás un correo de confirmación cuando tu firma haya sido validada exitosamente.</li> </ul> <b>📩 ¿Tienes dudas o necesitas ayuda?</b> <br><br> Si tienes inconvenientes con el proceso, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p> <div style='margin-top: 40px; font-size: 14px;'>Saludos,<br><br>El equipo de <b>MercadoFin</b></div> </div></body>"
				},
				{
					"nemonic" : "001-COD",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: ¡Validación código OTP!|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='font-family:sans-serif;width: 100% ; padding: 10px;'><p style='text-align:justify;font-weight:lighter'>Estimado(a) _name:<br><br>Firma Segura envía el código de validación _code para el ingreso y posterior firma del documento correspondiente a la transacción _idTransaction.</p><br>Saludos cordiales,<br>Firma Segura y MercadoFin<br><img src=\"_logoUrl\" alt=\"Firma Segura y MercadoFin\" style=\"max-width: 200px;\"><br><a href=\"https://www.mercadofin.com\">www.mercadofin.com</a></div>"
				},
				{
					"nemonic" : "001-FOTP",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: Código OTP para firmar tu solicitud #_idTransaction|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='font-size: 20px; font-weight: 600; font-family: sans-serif;margin-top: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%; height: auto;'></div>¡Código de verificación para completar tu firma!</div><div style='font-family:sans-serif;width:500px;padding:10px'><p style='text-align:justify;font-weight:lighter'>Estimado(a) _name,<br><br>Para continuar con el proceso de firma de tu <b>Solicitud #_idTransaction</b>, por favor ingresa el siguiente código en la plataforma: <p>🔐 <b>Código OTP: _code </b></p> <p><b>📌 Instrucciones para completar la firma:</b> <ul> <li> 1️⃣ Introduce tu código OTP en el campo correspondiente.</li> <li>2️⃣ Revisa y confirma la firma de los documentos requeridos.</li> <li>3️⃣ Recibirás una notificación cuando el proceso haya sido completado exitosamente.</li> </ul></p> <b>📩 ¿Necesitas ayuda?</b> <br> <br>Si tienes dudas o inconvenientes, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p><br><br>Saludos,<br><br>El equipo de <b>MercadoFin</b></div></body  >"
				},
				{
					"nemonic" : "001-CONF",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: [Solicitud #_idTransaction] ¡Firma completada, la aseguradora coordinará tu inspección vehicular!|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='width: 100%; font-family:sans-serif;'><div style='font-size: 20px; margin-top: 20px;font-weight: 600;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%;  height: auto;'></div>¡Firma completada exitosamente! </div> <div style='width:500px;padding:10px'>Estimado(a) _name,<br> <p> Se ha recibido y validado tu firma del <b>formulario de vinculación</b> para la <b>Solicitud #_idTransaction.</b> Ahora, el siguiente paso es la <b> inspección de tu vehículo</b>, un requisito necesario antes de la emisión de tu póliza de <b>Seguro Vehicular.</b></p> <b>🔎 Detalles de la transacción:</b> <ul> <li><b>Número de solicitud:</b> #_idTransaction</li> <li><b>Estado actual:</b> Firma completada</li> <li><b>Próximo paso:</b> Coordinación de inspección vehicular</li> </ul> <b>🚗 ¿Qué debes hacer ahora?</b> <br><br> Un inspector de <b>_establishment</b> se pondrá en contacto contigo para agendar la inspección. Asegúrate de estar disponible en la fecha acordada y de tener tu vehículo en condiciones óptimas para la revisión. <br><br> <b>📄 Visualiza tus documentos:</b> <br> \n <ul>\n _answer\n </ul>\n </p> <p><b>📩 ¿Tienes dudas o necesitas ayuda?</b> <br> Si necesitas más información, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p><br>Saludos, <br><br> El equipo de <b>MercadoFin</b> </div> </div>"
				},
				{
					"nemonic" : "002-INIT",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: ¡Validación para firma!|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%;  height: auto;'></div><div style='font-size: 22px; text-align: center; margin-top: 20px;'>¡Estás cerca de obtener tu Seguro!</div><div style='font-family:sans-serif;width:500px;padding:10px'><p style='text-align:justify;font-weight:lighter'>Estimado(a) _name, <br><br> El formulario de vinculación para _establishment, con ID de transacción _idTransaction, ha sido enviado para la firma. Te invitamos a ingresar al siguiente enlace: <a href=\"_contractURL\">Ver Formulario</a></p><br>Saludos cordiales,<br>Firma Segura y MercadoFin<br><a href=\"https://www.mercadofin.com\">www.mercadofin.com</a></div>"
				},
				{
					"nemonic" : "001-INSTS",
					"name" : "Solicitud de CONFIRMACIÓN",
					"message" : "subject¦MercadoFin: [Solicitud #_IDSolicitud] Nueva solicitud de _transaction enviada|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; margin: 0; padding: 0; '><div style='width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20x; margin-top: 20px; font-weight: 600;'>Nueva solicitud de _transaction</div><div style='margin-top: 20px;'><p>Estimado Broker,</p><p>Se ha generado una <b>nueva solicitud de _transaction (Solicitud #_IDSolicitud)</b> la cual requiere tu revisión para continuar con el proceso. Es necesario validar la documentación enviada por el usuario y determinar si se procede con una oferta comercial, se generan observaciones o se rechaza la solicitud.</p> <p>📌 <b>Detalles de la solicitud:</b> <ul><li><b>Número de solicitud:</b> #_IDSolicitud</li> <li><b>Estado actual:</b> Enviado</li> <li><b>Cliente:</b> _persona</li> <li><b>Vehículo:</b> Marca: _marca -- Modelo: _modelo -- Año: _ano</li></ul></p>  <p>📂 <b>Acceso a la documentación:</b> <br> <ul><li><b>Formulario de vinculación:</b> _plusListDigitalFolder</li> <li><b>Carpeta digital (almacenada en blockchain):</b> <a href='_link'>🔗 Carpeta Digital</a></li></ul></p>   <p>🔎 <b>Próximos pasos:</b> <br> <ul><li>1️⃣ Revisar la documentación enviada por el usuario para validar que cumpla con los requisitos.</li> <li>2️⃣ Determinar la acción a seguir: <ul><li>Si la información es correcta, generar y enviar la oferta comercial al usuario.</li> <li>Si hay inconsistencias, generar observaciones y notificar al usuario para corregirlas.</li> <li>Si no es viable la solicitud, proceder con el rechazo.</li></ul></li> <li>3️⃣ Actualizar el estado de la solicitud en la plataforma según la acción tomada.</li></ul></p> <p>📩 <b>¿Dudas o consultas?</b> <br><br> Para más información, el equipo de soporte está disponible en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p> <br> Saludos,<br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px; color: #888888; '>La firma de seguridad de esta transaccion es: <br> 🔑_hashtransaction</div></div></div>"

				},
				{
					"nemonic" : "001-USERS",
					"name" : "Solicitud de CONFIRMACIÓN",
					"message" : "subject¦MercadoFin: [Solicitud #_IDSolicitud] ¡Tu solicitud de _transaction ha sido enviada! |title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; font-weight: 600; margin-top: 20px;'>¡Tu solicitud de _transaction ha sido enviada!</div><div style='margin-top: 20px;'><p>Estimado(a) _persona,</p><p> La solicitud de <b>_transaction (Solicitud #_IDSolicitud) </b> ha sido enviada a la aseguradora para su evaluación. En esta etapa, la aseguradora revisará la información proporcionada y generará una oferta basada en los datos ingresados.</p><p>📌 <b>Detalles de la solicitud:</b> <ul><li><b>Número de solicitud:</b> #_IDSolicitud </li><li><b>Estado actual:</b> Enviado</li><li><b>Aseguradora:</b> _institution</li><li><b>Vehículo:</b> Marca: _marca -- Modelo: _modelo -- Año: _year</li></ul></p><p>🔎 <b>Próximos pasos:</b> <ul><li>1️⃣ La aseguradora evaluará tu solicitud y preparará una oferta de seguro.</li><li>2️⃣ Recibirás una notificación cuando la oferta esté lista para su revisión en la plataforma.</li><li>3️⃣ Deberás ingresar a MercadoFin para revisar los detalles y aceptar la oferta si estás de acuerdo.</li></ul></p><p><b>📩 ¿Tienes dudas o necesitas ayuda? </b> <br><br>Para más información, contáctanos en  <a href=\"mailto:soporte@mercadofin.com\">soporte@mercadofin.com</a>.</p></div><div style='margin-top: 0px; font-size: 14px;; '>Saludos,<br><br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px;'>La firma de seguridad de esta transacción es: <br>🔑_hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-OBS",
					"name" : "Solicitud de Observaciones",
					"message" : "subject¦MercadoFin: [Solicitud #_idInsurance] ¡Tu solicitud de seguro tiene observaciones!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding:20px '><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='margin-top: 20px;'></div><div style='font-size: 20px; font-weight: 600;margin-top: 20px;'>¡Revisa tu solicitud en MercadoFin!</div><div style='margin-top: 20px;'><p>Estimado(a) _persona,</p><p>Tu solicitud de seguro de vehículo ha recibido observaciones por parte de la aseguradora. Para continuar con el proceso, por favor revisa los detalles y realiza las correcciones necesarias. <br> <p><b>¿Qué debes hacer?</b></p> <ol> <li>Ingresa a la plataforma de <a href='https://mercadofin.com/'> MercadoFin </a> </li> <li>Accede a la sección de <b>''Solicitudes''</b></li> <li>Ve a la pestaña <b>''Estado Solicitudes''</b> y localiza tu solicitud de <b>''Seguros''</b></li> <li>Revisa las observaciones indicadas y realiza las correcciones necesarias.</li> </ol> <b>Observaciones: ⚠️</b> _observations <br><br> 📌 <b>Importante:</b> <br> <ul> <li>Completar las correcciones lo antes posible para evitar retrasos en el proceso.</li> </ul> 📩 <b>¿Necesitas ayuda?</b> <br> <br> Si tienes dudas o requieres asistencia, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p> </div><div style='margin-top: 40px; font-size: 14px; '>Saludos,<br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px;'>La firma de seguridad de esta transacción es:<br>🔑 _hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-ENDOFFER",
					"name" : "Solicitud de Oferta Final",
					"message" : "subject¦MercadoFin: [Solicitud #_idInsurance] ¡Tu oferta de Seguro de Vehículo está lista para revisar!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding:20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; font-weight: 600; margin-top: 20px;'>¡Se ha generado tu oferta de seguro vehicular!</div><div style='margin-top: 20px;'><p>Estimado(a) _persona,</p><p>Nos complace informarte que, a través de <b>MercadoFin</b>, se ha generado tu <b>oferta de Seguro de Vehículo</b> en representación de <b>_transaction,</b> con base en el formulario de solicitud que enviaste.</p> <b><p>Detalles de la oferta:</p></b> <table border='1' cellpadding='10' cellspacing='0' style='border-collapse: collapse; width: 100%; font-family: Arial, sans-serif;'><thead><tr style='background-color: #f2f2f2;'><th style='text-align: left;'>Concepto</th><th style='text-align: right;'>Detalle</th></tr></thead><tbody><tr><td>Tipo de seguro</td><td style='text-align: right;'>_tipoSeguro</td></tr><tr><td>Ciudad de emisión</td><td style='text-align: right;'>_city</td></tr><tr><tr><td>Marca del vehículo</td><td style='text-align: right;'> _brand </td></tr><tr><td>Modelo del vehículo</td><td style='text-align: right;'> _model </td></tr><tr><td>Versión del vehículo</td><td style='text-align: right;'> _version </td></tr><tr><td>Año del vehículo</td><td style='text-align: right;'> _year </td></tr><tr><td>Avalúo final del vehículo</td><td style='text-align: right;'>$ _initialValueOriginal </td></tr>  <tr><td>Valor final de la póliza</td><td style='text-align: right;'>$ _finalPolicyValue </td></tr></tbody></table> <p><b>📌 ¿Cuál es el siguiente paso?</b> <br><br> Si estás de acuerdo con la oferta, ingresa a la plataforma para completar el proceso y emitir tu póliza, siguiendo los siguientes pasos: <ol> <li>Ingresa con tu usuario a la plataforma de <a href='https://mercadofin.com/'> MercadoFin. </a> </li>  <li>Accede a la sección de <b>''Solicitudes''</b></li> <li>Ve a la pestaña <b>''Estado Solicitudes''</b></li> <li>Localiza tu solicitud de <b>''Seguros''</b> bajo el estado <b>''Propuesto''</b></li> <li>Revisa las condiciones usando el botón <b>''Ver oferta''</b></li> </ol> 📩 <b>¿Necesitas ayuda?</b> <br><br> Si tienes dudas o requieres asistencia, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p> </div><div style='margin-top: 40px; font-size: 14px;'>Saludos, <br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px;'>La firma de seguridad de esta transacción es:<br>🔑 _hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-REJECT",
					"name" : "Solicitud Rechazada",
					"message" : "subject¦MercadoFin: Solicitud #_idInsurance ¡Tu solicitud de seguro ha sido rechazada!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%;font-weight: 600; height: auto;'></div><div style='font-size: 20px; margin-top: 20px;'>¡Tu solicitud de seguro ha sido rechazada!</div><div style='margin-top: 20px;'><p>Estimado(a) _persona,</p><p>Lamentamos informarte que la aseguradora _transaction ha rechazado tu solicitud de _institution. <br><br> Puedes revisar más detalles y conocer los motivos del rechazo accediendo a la plataforma:  <a href='https://mercadofin.com/'> MercadoFin</a>, ingresando por ''Solicitudes'', ''Estado Solicitudes'', ''Seguros'' y ''Vigente/Rechazado''. <br><br>  <b>Detalles del rechazo</b> <br><br> 📌 <b>Motivo del rechazo:</b> _observations <br><br> 📌 <b>Siguiente paso:</b> Si deseas evaluar otras opciones de seguro, puedes generar una nueva solicitud a través de MercadoFin o contactarnos para recibir asesoría sobre las alternativas disponibles. <br><br> 📩 <b>¿Tienes dudas o necesitas ayuda?</b> <br><br> Escríbenos a <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>, estaremos encantados de asistirte.</p></div><div style='margin-top: 40px; font-size: 14px;'>Saludos, <br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px; '>La firma de seguridad de esta transacción es:<br>🔑 _hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-REGISTER",
					"name" : "Registro de usuario",
					"message" : "subject¦MercadoFin: ¡Registro de Usuario!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦registro_usuario|body¦<div style='font-family: sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><h3 style='font-weight: 400;'> <b>¡MercadoFin te da la bienvenida!</b> <br><br> Estimado(a) _name, <br> </h3><div><br /><div>Agradecemos tu interés en ser parte de esta comunidad. Para completar tu registro y garantizar la seguridad de tu cuenta, verifica tu dirección de correo electrónico siguiendo el siguiente paso: <br><ol><li>Haz clic en el enlace de verificación: <a href='_link'>MercadoFin</a></li></ol><b>¿No fuiste tú quien solicitó este registro?</b> <br> <br>Si este mensaje llegó por error, por favor escríbenos a <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>. <br><br> Gracias por confiar en MercadoFin. Estamos aquí para ayudarte a alcanzar tus metas financieras.</div></div><p>Saludos,</p> <p>El equipo de <b>MercadoFin.</b></p></div>"
				},
				{
					"nemonic" : "001-PASS-CHANGE-REQ",
					"name" : "Solicitud de cambio de contraseña",
					"message" : "subject¦MercadoFin: ¡Cambio de Contraseña!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦registro_usuario|body¦<div style='font-family: sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><h3 style='text-align: justify; font-weight: 400;'><span style=' font-weight: bold'>Solicitud de Cambio de Contraseña</span></h3><p>Hola _name,</p><p>Hemos recibido tu solicitud para cambiar la contraseña de tu cuenta en <span style=\"font-style:italic\">MercadoFin</span>. Para completar este proceso de forma segura, haz clic en el botón a continuación: <br> <a href='_link' style='margin-top: 10px; padding: 10px 20px; background-color: #4CAF50; color: white; text-decoration: none; border-radius: 5px; display: inline-block;'>🔒Cambiar Contraseña</a> <br><p><b>¿No solicitaste este cambio?</b></p><p>Si no reconoces esta acción, por favor ignora este correo o contáctanos de inmediato a través de nuestro equipo de soporte en:📩 <a href=\"mailto:soporte@mercadofin.com\">soporte@mercadofin.com</a>.</p><p>Estamos aquí para proteger tu seguridad y ayudarte con cualquier inconveniente.</p><div style='margin-top: 40px; font-size: 14px;'>Saludos,<br><p>El equipo de <b>MercadoFin.</b></p></div></div>"
				},
				{
					"nemonic" : "001-ENDOFFERHOME",
					"name" : "Solicitud de Oferta Final Vivienda",
					"message" : "subject¦MercadoFin: ¡Oferta por Seguro de Vivienda!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; text-align: center; margin-top: 20px;'>¡Se generó una oferta por Seguro de Vivienda!</div><div style='margin-top: 20px;'><p>Estimado(a) _persona,</p><p>Se informa que _transaction ha enviado la oferta en base al formulario. Para revisar, por favor ingresar a la plataforma mediante el siguiente <a href='https://mercadofin.com/profile/offers-received'> Link </a>. </p><table border='1' cellpadding='10' cellspacing='0' style='border-collapse: collapse; width: 100%; font-family: Arial, sans-serif;'><thead><tr style='background-color: #f2f2f2;'><th style='text-align: left;'>Concepto</th><th style='text-align: right;'>Valor</th></tr></thead><tbody><tr><td>Tipo de seguro</td><td style='text-align: right;'>_typeOfInsurance</td></tr><tr><td>Tipo de vivienda</td><td style='text-align: right;'>_typeOfHome</td></tr><tr><td>Año de construcción</td><td style='text-align: right;'>_yearsOfConstruction</td></tr><tr><td>Provincia</td><td style='text-align: right;'>_province</td></tr><tr><td>Ciudad de emisión</td><td style='text-align: right;'>_cityOfIssue</td></tr><tr><td>Forma de pago</td><td style='text-align: right;'>_methodOfPayment</td></tr><tr><td>Valor final de la póliza</td><td style='text-align: right;'>$_finalValueOfThePolicy</td></tr><tr><td>Valor final del avaluo</td><td style='text-align: right;'>$_finalValueOfAvaluo</td></tr></tbody></table></div><div style='margin-top: 40px; font-size: 14px;'>Saludos cordiales,<br>El equipo de MercadoFin</div><div style='margin-top: 40px; font-size: 10px;'>La firma de seguridad de esta transacción es:<br>🔑 _hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-SOLICITUD-FIRMA-USER",
					"name" : "Solicitud de CONFIRMACIÓN",
					"message" : "subject¦MercadoFin: [Solicitud #_idSolicitud] ¡Tu solicitud de firma electrónica está en proceso!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'> <div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; margin-top: 20px; font-weight: 600; '>¡Tu solicitud para _transaction ha sido enviada!</div> <div style='margin-top: 20px;'> <p>La solicitud para la generación de tu firma <b>electrónica P12</b> ha sido enviada y está en proceso. Para completar este trámite, en breve recibirás un <b>mensaje con el link de pago para tarjeta de crédito o débito.</b></p> <p>📌 <b>Detalles de la solicitud:</b> <br> <ul><li><b>Número de solicitud:</b> #_idSolicitud</li> <li><b>Estado actual:</b> Pendiente de pago</li> <li><b>Tipo de firma:</b> Digital P12</li></ul></p> <p> 📌 <b>Próximos pasos:</b> <br> <ul><li>1️⃣ Revisa tu bandeja de entrada en las próximas horas para recibir el mensaje con el link de pago.</li> <li>2️⃣ Accede al enlace y completa el pago con tarjeta de crédito o débito.</li> <li>3️⃣ Una vez confirmado el pago, recibirás una notificación cuando tu firma electrónica esté lista para su uso.</li></ul></p>  <p>📩 <b>¿Necesitas ayuda?</b> <br><br> Si tienes dudas o necesitas asistencia, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p></div> <div style='margin-top: 20px; font-size: 14px;'>Saludos, <br><br> El equipo de <b>MercadoFin</b></div></div>"
				},
				{
					"nemonic" : "001-SOLICITUD-FIRMA-INSTS",
					"name" : "Solicitud de CONFIRMACIÓN",
					"message" : "subject¦MercadoFin: [Solicitud #_idSolicitud] Nueva solicitud de firma electrónica en proceso|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; margin-top: 20px; font-weight: 600; '>¡Nueva solicitud de _transaction generada!</div> <p>Estimado(a) Administrador,</p> <p>Se ha generado una <b>nueva solicitud de firma electrónica P12 Solicitud #_idSolicitud</b> en la plataforma. A continuación, se presentan los detalles de la solicitud:</p> <p><b>📌 Detalles de la solicitud:</b> <br> <ul><li><b>Número de solicitud:</b> #_idSolicitud</li> <li><b>Estado actual:</b> Pendiente de pago</li> <li><b>Usuario:</b> _persona</li> <li><b>Correo registrado:</b> _mail </li> <li><b>Tipo de firma solicitada:</b> Digital P12</li></ul></p> <p><b>📌 Próximos pasos:</b> <br> <ul><li>1️⃣ El usuario recibirá un mensaje con el link de pago para tarjeta de crédito o débito.</li> <li>2️⃣ Una vez realizado el pago, la firma electrónica será generada y validada.</li> <li>3️⃣ Se enviará una notificación al usuario cuando la firma esté lista para su uso.</li></ul></p> <p><b>📄 Carpeta Documental</b></p> <ul><li>_plusListDigitalFolder</li> </ul><div style='margin-top: 40px; font-size: 14px; '>Saludos,<br><br>El equipo de <b>MercadoFin</b></div><div style='margin-top: 40px; font-size: 10px; '>La firma de seguridad de esta transacción es: <br> 🔑_hashtransaction</div></div>"
				},
				{
					"nemonic" : "001-USER-START-SIGNATURE",
					"name" : "Solicitud de Inicio de firma de Documentos.",
					"message" : "subject¦MercadoFin: [Solicitud #_idTransaction]  ¡Firma completada, validar documentación y coordinar inspección!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%;  padding: 20px; '><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; margin-top: 20px; font-weight: 600;'>¡Firma completada exitosamente!</div><div style='margin-top: 20px;'><p>Estimado Broker, </p><p>Te informamos que el usuario <b>_name</b> ha completado exitosamente el proceso de firma del <b>formulario de vinculación</b> para la <b>Solicitud #_idTransaction.</b></p>    <p><b>📌 Detalles de la transacción:</b> <br> <ul><li><b>Número de solicitud:</b> #_idTransaction</li> <li><b>Estado actual:</b> Firma completada</li> <li><b>Próximo paso:</b> Validar la documentación firmada por el usuario y asegurarse de que el inspector de <b> _establishment</b> se ponga en contacto con el cliente para coordinar la <b>inspección del vehículo.</b></li> </ul></p> <p> <b>🔎 Documentos disponibles para revisión</b> <br> \n    <ul>\n    _answer\n    </ul>\n </p> <p><b>📩 ¿Necesitas ayuda o más información?</b> <br><br> Si requieres más información, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p></div><div style='margin-top: 40px; font-size: 14px;'>Saludos,<br><br>El equipo de <b>MercadoFin</b></div></div>"
				},
				{
					"nemonic" : "001-BROKER-START-OF-SIGNATURE",
					"name" : "Solicitud de firma",
					"message" : "subject¦MercadoFin: <b>[Solicitud # _idTransaction]</b> Usuario aceptó la oferta de Seguro Vehicular.|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='width: 100%; font-family: sans-serif;padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; font-weight: 600; margin-top: 20px;'>¡El usuario arrancó con el inicio de firma!</div> <div style='font-family:sans-serif;width:500px; padding:10px'> <p style='text-align:justify;font-weight:lighter'>Estimado Broker, <br><br> <p>Te informamos que el usuario _name ha aceptado la oferta de Seguro Vehicular y podría iniciar el proceso de firma de documentos. para la Solicitud # _idTransaction.</p> <p>📌 <b>Detalles de la solicitud:</b> <br> <ul><li><b>Número de solicitud:</b> # _idTransaction</li> <li><b>Tipo de seguro:</b> Vehicular</li> <li><b>Estado actual:</b> Firma</li></ul></p>  <p>🔎 <b>Siguientes pasos:</b> <br> <ul><li>Aguardar la notificación de confirmación una vez que el usuario complete la firma.</li> <li>En caso de existir observaciones sobre el formulario de vinculación, realizar la validación correspondiente dentro de la plataforma.</li></ul></p>  <p>📩 <b>¿Dudas o consultas?<br><br></b> Si necesitas más información, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>. </p> <div style='margin-top: 40px; font-size: 14px;'>Saludos,<br><br>El equipo de <b>MercadoFin</b></div> </div></div>"
				},
				{
					"nemonic" : "001-INSPECCION",
					"name" : "Solicitud de inpeccion",
					"message" : "subject¦MercadoFin: [Solicitud # _idTransaction] Inspección aprobada, tu póliza está en proceso de emisión |title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; margin-top: 20px; font-weight: 600;'>¡Tu inspección ha sido aprobada!</div><div style='margin-top: 20px;'><p>Estimado(a) _name, </p> <p>Nos complace informarte que la inspección de tu vehículo ha sido aprobada exitosamente por el inspector de <b>_institution.</b> Ahora, la aseguradora ha iniciado el proceso de <b>emisión de tu póliza,</b> lo que significa que estás a un paso de completar la contratación de tu Seguro Vehicular <b>(Solicitud # _idTransaction).</b></p> <p>📌 <b>¿Cuál es el siguiente paso?</b> <br>  <ul><li>✅ La aseguradora está procesando la emisión de tu póliza.</li> <li>✅ Una vez generada, recibirás una notificación con los documentos de tu seguro.</li></ul>  </p> <p><b>📩 ¿Tienes dudas o necesitas ayuda?</b> <br> <br> Si necesitas más información, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>. </p> </div><div style='margin-top: 20px; font-size: 14px;'>Saludos,<br><br>El equipo de <b>MercadoFin</b></div></div>"
				},
				{
					"nemonic" : "001-SEND-REMINDER",
					"name" : "Solicitud Recordatorio de Firma",
					"message" : "subject¦MercadoFin: [Solicitud #_idSolicitud] ¡Recuerda completar la firma de tu Seguro Vehicular!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px; '><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 20px; font-weight: 600; margin-top: 20px;'>¡No olvides completar tu firma para obtener tu seguro!</div> <div style='margin-top: 20px;'><p>Estimado(a) _persona,</p> <p>Notamos que aún no has completado el proceso de firma de los documentos asociados a tu Seguro Vehicular <b>Solicitud #_idSolicitud.</b> Este es el último paso antes de la emisión de tu póliza.</p> <p><b>Accede ahora y finaliza la firma:</b> 🔗 <a href='_link'> Firma Segura</a>    </p> <p> 📌 <b>¿Cómo completar la firma?</b> <ul> <li>1️⃣ Ingresa al portal de firma a través del enlace anterior.</li> <li>2️⃣ Inicia sesión con tu correo registrado en MercadoFin.</li> <li>3️⃣ Revisa los documentos generados, incluyendo el formulario de vinculación.</li> <li>4️⃣ Firma electrónicamente siguiendo las instrucciones en pantalla.</li> <li>5️⃣ Finaliza el proceso y aguarda la confirmación por correo.</li> </ul> </p> <p> ✅ <b>Importante:</b> <ul> <li>Asegúrate de completar la firma dentro del tiempo estipulado para evitar retrasos en la emisión de tu póliza.</li> <li>Recibirás un correo de confirmación cuando tu firma haya sido validada exitosamente.</li> </ul></p> <p>📩 <b>¿Tienes dudas o necesitas ayuda?<br><br></b> Si tienes inconvenientes con el proceso, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>.</p></div> <div style='margin-top: 40px; font-size: 14px; '>Saludos,<br><br> El equipo de <b>MercadoFin</b></div></div>"
				},
				{
					"nemonic" : "001-GEN-OFFER-REMINDER",
					"name" : "Solicitud Recordatorio de oferta",
					"message" : "subject¦MercadoFin: [Solicitud #_idSolicitud] ¡Recuerda revisar y aceptar tu oferta de seguro!|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif; width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div> <div style='font-size: 22px; margin-top: 20px;'>¡Tu oferta de seguro sigue pendiente de revisión!</div> <div style='margin-top: 20px;'><p>Estimado(a) _persona,</p> <p>Te recordamos que tienes una <b>oferta de _typeInsurance </b> pendiente de revisión y aceptación en la plataforma. Completar este paso es esencial para continuar con la adquisición de tu póliza vehicular.</p> <p>🔎 <b>Revisa los detalles y acepta tu oferta aquí:</b> 🔗 <a href='https://mercadofin.com/'> Ingresar a MercadoFin</a></p> <p>📌 <b>Pasos rápidos para revisar tu oferta:</b> <ul><li>1️⃣ Ingresa a la plataforma de MercadoFin con tu usuario y contraseña.</li> <li>2️⃣ Dirígete a la sección <b>''Solicitudes''</b> en el menú principal.</li> <li>3️⃣ Haz clic en la pestaña <b>''Estado Solicitudes''</b> para ver el estado actual de tus trámites.</li> <li>4️⃣ Selecciona la categoría <b>''Seguros''</b> para filtrar las solicitudes relacionadas con seguros.</li> <li>5️⃣ Busca tu Solicitud #_idSolicitud bajo el estado <b>''Propuesto''</b> y haz clic en el botón <b>''Ver oferta''.</b></li> <li>6️⃣ Revisa los detalles de la oferta y, si estás de acuerdo, procede con la aceptación para continuar el proceso.</li> </ul></p> <p>📩 <b>¿Necesitas ayuda?</b> Si tienes dudas o requieres asistencia, contáctanos en soporte@mercadofin.com </p></div> <div style='margin-top: 40px; font-size: 14px; '>Saludos, <br><br>El equipo de <b>MercadoFin</b></div></div>"
				},
				{
					"nemonic" : "017-INVOICE",
					"name" : "Factura electronica",
					"message" : "subject¦Factura Electrónica: _idInvoice|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style=\"background: #eee; padding: 25px;\"><header style=\"margin-top: 25px;\"></header>\n<div style=\"margin-top: 50px;\">\n<p><strong>MercadoFin</strong></p>\n<p>&nbsp;</p>\n<p>Estimad@ _name,</p>\n<p>En los siguientes enlaces puede ver el pdf y el xml de su factura electrónica:  <a href=\"_ipfsPdf\">Ver Pdf</a>&nbsp;&nbsp;<a href=\"_ipfsXml\" download=\"xml_factura.txt\">Ver Xml</a></p>\n<p>&nbsp;</p>\n<p>Saludos,</p>\n<p>E Process Med</p>\n</div>\n<footer style=\"text-align: center; margin-top: 50px;\"><img src=\"_logoUrl\" alt=\"logo_firma_digital\" /></footer></div>|bcc¦bcc-12345678@yopmail.com"
				},
				{
					"nemonic" : "001-COORDINATE-INSPECTION",
					"name" : "Solicitud de Cordinar inspección",
					"message" : "subject¦🚗 MercadoFin: [Solicitud #_idTransaction] Coordinar inspección vehicular|title¦Mercado Fin|sender¦no-reply@firmasegura.digital|type¦envio_credito|body¦<div style='font-family: Arial, sans-serif;  width: 100%; padding: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='imagen' style='max-width: 100%; height: auto;'></div><div style='font-size: 22px; margin-top: 20px; font-weight: bold; '>Nueva solicitud de inspección vehicular</div> <p>Estimado(a) Inspector,</p> <p> Se ha generado una solicitud de inspección vehicular para la <b>Solicitud #_idTransaction.</b> A continuación, te proporcionamos los datos ingresados por el usuario para que puedas coordinar la visita.</p> <p><b>📌 Detalles de la inspección:</b> <br> <ul><li><b>Número de solicitud:</b> #_idTransaction </li> <li><b>_typeSelectDays</b> _days </li> <li><b>_typeSelectHours</b> _hours </li> <li><b>Dirección de inspección:</b> _address </li></ul></p> <p>📞 <b>Siguiente paso:<br><br></b> Por favor, <b>contacta al cliente para confirmar la fecha y hora de la inspección</b> considerando de los horarios sugeridos. Una vez realizada la inspección, actualiza el estado en la plataforma para continuar con el proceso de emisión de la póliza.</p> <p><b>📩 ¿Necesitas más información?<br><br></b> Si tienes dudas o requieres asistencia, contáctanos en <a href='mailto:soporte@mercadofin.com'>soporte@mercadofin.com</a>. </p> <div style='margin-top: 40px; font-size: 14px;'>Saludos,<br><br>El equipo de <b>MercadoFin</b></div></div>"
				}
			]
		}
	}
})



//Insert plantilla
db.clients.updateOne(
    { "estbMnemonic": "MF" }, // Filtro para encontrar el documento correcto
    { 
        $push: { 
            "channels.email.campaigns": {
                "nemonic": "001-MORE-INFORMATION",
                "name": "Solicitud de más información",
                "message": "subject¦MercadoFin: Tipos de Firma Electrónica|title¦Solicitud de firma|sender¦no-reply@firmasegura.digital|type¦firma_digital|body¦<div style='font-size: 22px; margin-top: 20px;'><div style='text-align: center;'><img src='https://dev.mercadofin.com:18080/ipfs/QmNVU4fo7hiFHCt7suaZZ1edgJ5iASDf5QYQVUvBQ2n5op' alt='Logo de MercadoFin' style='max-width: 100%; height: auto;'></div>  <div style='font-family:sans-serif;width:500px;padding:10px'>Estimado(a) _fullName,<br><br> <p>Agradecemos el interés por adquirir información detallada correspondiente al tipo de firma electrónica seleccionada.</p> <p>Contamos con tus datos:</p> <p> <ul><li><b>Correo electrónico:</b> _email </li>  <li><b>Número de contacto:</b> _phone</li> </ul> </p>   <p>📩 Enviaremos la información solicitada en el transcurso de los próximos minutos.</p>  <br>Saludos, <br><br> El equipo de <b>MercadoFin</b></div></div>"
            }
        }
    }
);



//Delete por 
//db.clients.deleteOne({ estbMnemonic: "MF" });
